//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class dbEntities : DbContext
    {
        public dbEntities()
            : base("name=dbEntities")
        {
            Database.SetInitializer<DbContext>(null);
        }


        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<eierskap> eierskap { get; set; }
        public virtual DbSet<forfattere> forfattere { get; set; }
        public virtual DbSet<forskning> forskning { get; set; }
        public virtual DbSet<institutter> institutter { get; set; }
        public virtual DbSet<person> person { get; set; }
        public virtual DbSet<rank> rank { get; set; }
        public virtual DbSet<rankinstitusjon> rankinstitusjon { get; set; }
        public virtual DbSet<stopwords> stopwords { get; set; }
        public virtual DbSet<tidsskrift> tidsskrift { get; set; }
        public virtual DbSet<tilhorighet> tilhorighet { get; set; }
        public virtual DbSet<titles> titles { get; set; }
        public virtual DbSet<wordcloud> wordcloud { get; set; }
        public virtual DbSet<words> words { get; set; }
        public virtual DbSet<basewords> basewords { get; set; }
    }
}
