//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbEntities : DbContext
    {
        public dbEntities()
            : base("name=dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Person> person { get; set; }
        public virtual DbSet<Rank> rank { get; set; }
        public virtual DbSet<Stoppord> stoppord { get; set; }
        public virtual DbSet<Tidsskrift> tidsskrift { get; set; }
        public virtual DbSet<Tilhorighet> tilhorighet { get; set; }
        public virtual DbSet<Titler> titler { get; set; }
        public virtual DbSet<Ordsky> ordsky{ get; set; }
        public virtual DbSet<Rotform> rotform { get; set; }
        public virtual DbSet<Oppslagsord> oppslagsord { get; set; }
        public virtual DbSet<Forfattere> forfattere { get; set; }
        public virtual DbSet<Forskning> forskning { get; set; }
    }
}
