//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class words
    {
        public int key { get; set; }
        public string word { get; set; }
        public int count { get; set; }
    
        public virtual ICollection<wordcloud> wordcloud { get; set; }
 
        public virtual ICollection<basewords> basewords { get; set; }
    }
}
